src/controllers/Router.ts
src/types/Router.ts

[_Add Router_](https://trello.com/c/QzMwHxc9)
Маршрут добавляется методом `route`. Первый параметр - путь, второй - функция генерирующая нужный контент
```js
const router = new Router();
const view = new View();
router.route('/', view.renderMain.bind(view));
router.route('/page-1', view.renderPage1.bind(view));
router.route('/page-2', view.renderPage2.bind(view));
router.route('/book/:chapter/:page', view.renderBook.bind(view));
```
Параметры необходимые для генерации контента добавляются в путь в формате `:param`

feat: Add Router

---

.eslintrc.json

Что б избежать такого кол-ва пустых строк, предлагаю использовать настройку еслинта

fix: lines-between-class-members

---

src/models/State.ts

[Add State](https://trello.com/c/oxOrlu5U)
Добавил модель стейта.
По совету Валеры добавил в него константы API.
Добавил кол-во глав в учебнике и страниц в главе.

feat: add State model

---

src/utils/customElement.ts

[[FE] Create custom element class](https://trello.com/c/aFprKyJn)
_Создать div_
const newDiv = new CustomElement('div', { className: 'div', id: 'id', textContent: 'text' })
_Создать button_
const newButton = new CustomElement('button', { className: 'button', id: 'idB', textContent: 'button' })
_Сделать button ребенком div_
newDiv.addChildren([newButton.element])

feat: add custom element class

---

src/controllers/Events.ts
src/types/Events.ts

[add Observer](https://trello.com/c/ViRE8jUD)
Использовать:
```js
const events = new Events();
events.subscribe('testEvent', () => console.log('Event test'));
events.notify('testEvent'); // console.log('Event test')
```
добавить свой ивент:
```js
interface ObserverEvents {
testEvent: string;
}
```

feat: Events

---

src/api/words/wordsApi.ts
src/index.ts

fix: words api path

---

src/controllers/user.ts
src/types/IUser.ts

refactor: add isAuthorized property

---

src/controllers/App.ts
src/controllers/user.ts
src/types/IUser.ts
src/types/State.ts

refactor: user.constructor

---

src/controllers/App.ts
src/controllers/user.ts

fix: string 2 null

---

.github/workflows/github-actions.yml
.stylelintrc.json
package.json
src/scss/abstracts/_isActive.scss
src/scss/pages/_bookPage.scss

[add stylelint test](https://trello.com/c/tY72plYo)
Добавлены тесты stylelint.
Использовать `npm run style`
Исправлены ошибки стилей

feat: add stylelint test

---

src/controllers/App.ts
src/types/HeaderTypes.ts
src/views/MainLayout.ts
src/views/components/header.ts
src/views/renderLayout.ts

(https://trello.com/c/DnaWmMIl)
add state.user.isAuthorized to updateHeader()

fix: add state.user.isAuthorized to updateHeader()

---

src/scss/components/_footer.scss
src/scss/components/index.scss
src/scss/index.scss
src/views/components/footer.ts

feat: add rslogo style

---

src/views/components/dialogSignUp.ts

refactor: signUp dialog

---

src/api/users/usersWordsApi.ts
src/controllers/User.ts

Fixed aggregated words filters.

fix: aggregated words filters

---

src/models/Config.ts

[Перенести сервер на HTTPS](https://trello.com/c/T8ekttst)
Теперь деплой на нетлифай фай не должен давать ошибки

refactor: change url

---

src/views/View.ts

[_Footer_](https://trello.com/c/DtZg0qaM)
Если в рендер метод в аппенд добавить this.footerElement, футер будет. Иначе, не будет

feat: footer correction

---

src/views/pages/audioChallengePage.ts
src/views/pages/sprintPage.ts

фикс бага с запуском игры со страницы игр, после игры из учебника

fix:  restart game from game page

---

src/controllers/App.ts

fix: reboot page routing

---

src/views/components/header.ts

fix: sign in button

---

src/controllers/AudioChallengeController.ts

Пофиксил в игре баг с CORS, если запросов очень много
просто сделал их меньше)

fix: audio-challenge CORS ERR

---

src/views/components/header.ts

fix: logout

---

src/views/pages/sectionPage.ts

Была проблема с появлением ошибок в консоли при построении страницы с карточками у неавторизованного пользователя.

fix: bug with words

---

src/views/AudioChallengeView.ts
src/views/View.ts
src/views/pages/audioChallengePage.ts

Добавил управление с клавиатуры

feat: add key control

---

src/controllers/AudioChallengeController.ts

fix: game stat update

---

src/controllers/User.ts
src/views/View.ts
src/views/pages/statisticPage.ts

[Добавить страницу статистики](https://trello.com/c/1cizbX4X)
[Статистика за день](https://trello.com/c/zSN1d0id)
Добавил страницу статистики  и блок статистики за день

feat: add Today statistic

---

src/views/components/sprintResults.ts

fix: statistic error

---

src/views/View.ts

fix: footer to body

---

src/scss/components/_burger.scss
src/views/components/burger.ts
src/views/components/header.ts
src/views/pages/sectionPage.ts

[_меню_](https://trello.com/c/42TsM9To)
Обновила поведение меню при кликах вне меню.

fix: menu listeners

---

src/controllers/AudioChallengeController.ts
src/types/Events.ts
src/views/AudioChallengeView.ts
src/views/View.ts

Добавил вывод, если все слова на странице изученны.

fix: add no words page

---

src/views/components/sprintResults.ts

Пофиксил баг с удаление чужой статистики

fix: update statistic bug

---

src/scss/components/_statistic.scss
src/scss/components/index.scss
src/views/View.ts
src/views/pages/statisticPage.ts

[add statistic for all time](https://trello.com/c/rx5QcSsI)
Статистика за все время (без стилей)

feat: add statistic for all time

---

src/scss/components/_burger.scss

fix: menu z-index

---

src/scss/components/_footer.scss

На статистике треугольник обрезался

fix: footer

---

src/scss/components/_layout.scss
src/scss/components/_spinner.scss
src/scss/components/index.scss
src/views/AudioChallengeView.ts
src/views/View.ts
src/views/pages/sprintPage.ts

переписал спиннер на диалог, что б он был всегда в середине экрана.

refactor: spinner

---

src/models/Config.ts
src/scss/pages/_bookPage.scss
src/views/pages/bookPage.ts

feat: book page styles

---

src/views/View.ts
src/views/components/header.ts

fix: login style

---

src/views/View.ts

- [x Refactoring
Удалил закоментированый код

refactor: delete comments

---

src/scss/components/_layout.scss

fix: html styles

---

src/scss/pages/_gamesPage.scss
src/scss/pages/_sprintPage.scss

Марджины, чтобы треугольник не наплывал на текст мйена

fix: games footers

---

src/views/components/WordCardClass.ts
src/views/components/burger.ts
src/views/pages/bookPage.ts
src/views/pages/mainPage.ts
src/views/pages/sectionPage.ts

[fix: signUp routing](https://trello.com/c/uB1ulVWJ)
теперь диалог закрывается корректно

fix: routing SignUp

---

src/controllers/AudioChallengeController.ts
src/models/AudioChallengeModel.ts
src/views/AudioChallengeView.ts
src/views/View.ts
src/views/components/sprintGameStart.ts

[Убирать слушатель после игры](https://trello.com/c/81nWRo7u)
fix: remove game's keyListener

fix: remove keyListener audioChallenge

---

src/scss/components/_layout.scss
src/scss/components/_statistic.scss

[Выровнять блок отсутствующей статистики](https://trello.com/c/Ac7eIhmG)
Выровнял блок отсутствующей статистики

fix: zero statistic layout

---

src/assets/icons/close.svg
src/scss/abstracts/_colors.scss
src/scss/components/_dialog.scss
src/scss/components/_form.scss

[Сверстать signIn/signUp](https://trello.com/c/C4upYkpv)

refactor: signIn/signUp styles

---

src/scss/components/_statistic.scss
src/views/pages/statisticPage.ts

Поправила немного стиль надписи об отсутствии статистики

fix: empty statistic

---

src/scss/components/_burger.scss
src/views/components/burger.ts

Стилизованное бургер меню.
Без анимации появления.
Без смены палок в значке меню.
Доделаем, если будет время. 
Пока такой вариант рабоче-итоговый.

feat: burger menu style

---

src/scss/components/_layout.scss
src/scss/pages/_sprintPage.scss

Cтилизация скроллов - главный на странице и скроллы в статистике по итогу миниигр

feat: scroll style

---

src/scss/components/_layout.scss
src/scss/pages/_about.scss
src/scss/pages/_main.scss
src/scss/pages/index.scss
src/views/View.ts
src/views/pages/aboutUsPage.ts
src/views/pages/mainPage.ts

[Сверстать About](https://trello.com/c/XUq8aQED)
Сверстал About

feat: about styles

---

src/scss/pages/_about.scss

fix: margin

---

src/scss/components/_form.scss
src/views/components/dialogSignIn.ts
src/views/components/dialogSignUp.ts

fix: password type

---

src/scss/pages/_about.scss
src/scss/pages/_main.scss
src/views/pages/mainPage.ts

Переделал главную, фикс о нас
Теперь минимальная ширина экрана 1024px.

fix: block size

---

src/scss/components/_ballsAnimation.scss
src/scss/pages/_main.scss
src/views/pages/mainPage.ts

Теперь шары на главной качаются

feat: add main page balls animation

---

src/scss/components/_layout.scss
src/scss/pages/_gamesPage.scss

fix: games page

---

src/views/View.ts

fix: scroll

---

src/scss/pages/_audioChallengePage.scss

Лишние марджины, которые мешали, когда в блоке много контента

fix: fix audio challenge styles

---

src/scss/components/_burger.scss

Фикс не активной ссылки в меню

fix: menu link

---

src/scss/pages/_main.scss
src/views/View.ts

fix: height

---

src/controllers/App.ts
src/controllers/AudioChallengeController.ts
src/views/components/dialogSignUp.ts
src/views/components/sprintResults.ts
src/views/pages/statisticPage.ts

refactor: del log

---

src/views/pages/statisticPage.ts

fix: stats
